### ISSUE TITLE
Criar ambiente conda para manipular o SCANPLOT

### ISSUE THREAD

**Issue by Garcia-INPE** [cfbastarz/SCANPLOT#17]
Após o clone do repositório do SCANPLOT: 
- git clone https://github.com/GAM-DIMNT-CPTEC/SCANPLOT.git

Checar prioridade de busca dos pacotes a serem instalados
- conda config --set channel_priority flexible

OBS: com strict a criação não funcionou
"Your installed version is: 4.4.0. Note that strict channel priority may have removed packages required for satisfiability." 
Mensagem após MUUUUUUITO tempo

Entrar no diretório SCANPLOT
- cd SCANPLOT

Criar o ambiente com:
- conda env create -f environment.yml

Ativar o ambiente SCANPLOT
- conda activate SCANPLOT

Instalar o SCANPLOT
- pip install -e .

Abrir o notebook - a partir do diretório.../SCANPLOT
- jupyter notebook SCANPLOT.ipynb

Para executar precisei:
- conda install hvplot

**Comment by cfbastarz** [comment]
Obrigado Zé Roberto pelo report deste problema. O pacote `hvplot`será adicionado ao arquivo `environment.yml`.

**Comment by cfbastarz** [comment]
Foram atualizandos os arquivos `master/environment.yml` com as novas dependências (hvplot e outros) e `main/docs/instalacao.md` com instruções referentes ao flexible solve do conda. A atualização do arquivo de ambiente quebrou a build do container do Binder. Para resolver, foi criado o branch binder_test onde serão realizados alguns testes. Quando estiver resolvido, será feito um pull requeste deste branch para o master.

**Comment by cfbastarz** [comment]
O pull request #18 resolver o problema do ambiente Python para uso do SCANPLOT em máquina local e no Binder.
